### ISSUE TITLE
Handle much address like 1 million address

### ISSUE THREAD

**Issue by anggaand123** [aceat64/EasyBitcoin-PHP#16]
Hi ..
i try want to build website with API service provider like
block.io

so i compile bitcoin-cli daemon in 1 vps. and created 1 vps more for backend using php
and i connected with your library

now i have a 25k address in my bitcoin wallet.dat .
and now i feel the proccess is slow .
what the best technical for this case ?? 
any help ?
sory for oot

**Comment by knkrth** [comment]
EasyBitcoin-PHP is a light weight API it can't handle that much load. If you want you can use https://github.com/bitpay/insight-api for heavy production use.
