### ISSUE TITLE
Username / Password ?

### ISSUE THREAD

**Issue by michaelsomerville** [aceat64/EasyBitcoin-PHP#17]
Looking at the code here ...
What site are you calling the username/password for ? What is this connected too.

thanks, great work too!

**Comment by aceat64** [comment]
This library is used for talking to the JSON-RPC API of a Bitcoin node, specifically a Bitcoin Core node (as I don't bother to test against alt-coins or forks).

**Comment by michaelsomerville** [comment]
Oh, so we have to have a full node running to use this - not up on that stuff yet.
