### ISSUE TITLE
Username Password

### ISSUE THREAD

**Issue by AqeelKazmi** [aceat64/EasyBitcoin-PHP#19]
Hi
To make this connection ====>
$bitcoin = new Bitcoin('username','password');
From where i get this username  and password..Please guide me

**Comment by aceat64** [comment]
This library is used for talking to the JSON-RPC API of a Bitcoin node, specifically a Bitcoin Core node (as I don't bother to test against alt-coins or forks).

**Comment by AqeelKazmi** [comment]
apart from this, i just want to know that ,is it necessary for test network to have bitcoin daemon installed? Is bitcoin daemon plays a role of full node?
Kindly answer my queries .
Thanks in advance

**Comment by aceat64** [comment]
You will need this software:

https://bitcoin.org/en/download
