### ISSUE TITLE
Is there a way to specify the wallet file?

### ISSUE THREAD

**Issue by gdfbacchus** [aceat64/EasyBitcoin-PHP#21]
I'm running bitcoind with multiple wallets since they just added the support for it in their last release. However, I don't see any way to specify the .dat file for the wallet here. Is this possible? If so, how would I do this?

**Comment by aceat64** [comment]
I believe you should be able to specify it when initializing the Bitcoin connection/object.

```php
$bitcoin = new Bitcoin('username', 'password', 'localhost', 8332, '/wallet/otherwallet.dat/');
```

I haven't tested it though.
