### ISSUE TITLE
"JSON value is not an integer as expected"

### ISSUE THREAD

**Issue by rawmaterials** [aceat64/EasyBitcoin-PHP#23]
trying to get block 502284 

$bitcoin->getblockhash('502284') 

getting

(
    [result] =>
    [error] => Array
        (
            [code] => -1
            [message] => JSON value is not an integer as expected
        )

    [id] => 1

**Comment by aceat64** [comment]
You need to send it as an integer, not a string. Example:

```php
$bitcoin->getblockhash(502284);
```

Note the lack of quotes.

**Comment by Lancelight** [comment]
I ran across this same problem,  below is how I solved this without having to typeset anything.  I added this in the __call() function of the class.  With the following addition, both "1234" and 1234 will work just fine.

```
//Make sure numeric values have the right type
foreach ($params AS $key => $arg)
{
   if (isset($arg))
   {
      //RPC is typesetting sensitive, so make sure any number is a float.  For some reason bitcoin RPC daemons consider "float" as an INT as well as a Float.  So this covers both types of numerical values that PHP provides.
      if (is_numeric($arg))
      {
         if (strval($arg) == (float)$arg)
         {
            $params[$key] = (float)$arg;
         }
      }
   }
}
```
