### ISSUE TITLE
why incementing id?

### ISSUE THREAD

**Issue by mo29cg** [aceat64/EasyBitcoin-PHP#25]
```
  // The ID should be unique for each call
        $this->id++;
```
why do you need this?
if id is always 0, and not unique for each call, what will happen?
when I checked with some commands, it seemed fine.

sorry for my english.

**Comment by aceat64** [comment]
It's just part of the [JSON RPC spec](http://www.jsonrpc.org/specification#request_object). It may not be strictly necessary, but it's easy enough to do.
