### ISSUE TITLE
Empty reply from server

### ISSUE THREAD

**Issue by faanigee** [aceat64/EasyBitcoin-PHP#30]
hello dear i m trying to use easybitcoin to connect my bitcoind daemon to get wallet info and etc etc.
i m using bitcoin.conf file 

server=1
daemon=1
rpcallowip=connecting server ip/0
rpcuser=username of mine
rpcpassword=password
rpcport=8333
listen=1
keypool=10000
prune=600
maxuploadtarget=20
maxconnections=16
walletnotify=/var/www/html/cron/receive.sh %s

and in easy bitcoin i m connecting like this

<?php
require('easybitcoin.php');
$bitcoin = new Bitcoin('username of mine', 'password', '139.59.xx.xxx', '8333','http');
print_r($bitcoin);
echo "</Br>";
$info = $bitcoin->getinfo();
print_r($info);
echo "<br>";
print_r($bitcoin->getwalletinfo() );
echo"<br>";
echo $info ? $info : "Oops an error: ".$bitcoin->error;
?>

it give me output 
Empty server reply

what is wrong in my code please any one help me????

**Comment by erikdubbelboer** [comment]
How do you set `$bitcoin`?

**Comment by cxla** [comment]
me same problem, this is lie code
