### ISSUE TITLE
NULL value returned for call

### ISSUE THREAD

**Issue by ebiboy2** [aceat64/EasyBitcoin-PHP#36]
i tried to run a command that has the following structure `bitcode-cli getaddressdeltas '{"addresses": ["Bh22SsBJyeAJY3vmc8EEd12HWMtM85c7C0"]}'` using the EasyBitcoin-PHP script but it returns NULL. How can i modify the code to accept the command?

**Comment by aceat64** [comment]
That doesn't appear to be a Bitcoin API call, I only support use-cases involving Bitcoin.

Please note, you will likely be better off using [php-bitcoinrpc](https://github.com/denpamusic/php-bitcoinrpc) as it is much more actively maintained.
