### ISSUE TITLE
bitcoind won't send bitcoins from wallet

### ISSUE THREAD

**Issue by riksanches** [aceat64/EasyBitcoin-PHP#38]
I'm using library for PHP https://github.com/aceat64/EasyBitcoin-PHP

I'm trying to unlock wallet using

`<?php

require 'func/ezbtc.php';

$bitcoin = new Bitcoin('admin','admin', 'localhost', '7788');

$bitcoin->walletpassphrase('PASSWORD', '30');

?>`

Instead of PASSWORD there is real password for wallet.

But when I try to send some bitcoins to another wallet it just not working.
No errors, nothing.

What's wrong?

**Comment by riksanches** [comment]
var_dump($bitcoin->sendtoaddress('1Headz2mYtpBRo6KFaaUEtcm5Kce6BZRJM', 0.00000001));

returns bool(false)

**Comment by Rezureaxx** [comment]
Same problem here
