### ISSUE TITLE
CURLOPT_FOLLOWLOCATION clashes with PHP's open_basedir directive

### ISSUE THREAD

**Issue by stolendata** [aceat64/EasyBitcoin-PHP#4]
EasyBitcoin-PHP should enable `CURLOPT_FOLLOWLOCATION` only if `ini_get( 'open_basedir' )` returns FALSE or an empty string.

https://github.com/stolendata/rpc-ace#caveats

**Comment by Srichon** [comment]
[1. ]([url]( #26 ))
